export { default as HomeView } from './HomeView.vue'
export { default as LoginView } from './LoginView.vue'
export { default as CollectionListView } from './collection/CollectionListView.vue'
export { default as CollectionCreateView } from './collection/CollectionCreateView.vue'
export { default as CollectionUpdateView } from './collection/CollectionUpdateView.vue'
export { default as FurnitureListView } from './furniture/FurnitureListView.vue'
export { default as FurnitureCreateView } from './furniture/FurnitureCreateView.vue'
export { default as FurnitureDetailView } from './furniture/FurnitureDetailView.vue'
