# Use tech_user/secret as user/password credentials
version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: dssd-furniture-frontend
      dockerfile: Dockerfile
    expose:
      - 3000
  
  backend:
    container_name: backend
    build:
      context: dssd-furniture-backend
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - static-volume:/home/app/web/staticfiles
      - static-media:/home/app/web/mediafiles
  
  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ljj_muebles
      POSTGRES_USER: ljj_muebles
      POSTGRES_PASSWORD: admin
    volumes:
      - db-volume:/var/lib/postgresql/data/
  
  nginx:
    container_name: nginx 
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static-volume:/home/app/web/staticfiles
      - static-media:/home/app/web/mediafiles

volumes:
  db-volume:
  static-volume:
  static-media: