# Use tech_user/secret as user/password credentials
version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: dssd-furniture-frontend
      dockerfile: Dockerfile
    expose:
      - 3000
    networks:
      mynetwork:
        ipv4_address: 172.25.0.2  # Assign the desired IP address
  
  backend:
    container_name: backend
    build:
      context: dssd-furniture-backend
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      DB_NAME: ljj_muebles 
      DB_USER: ljj_muebles 
      DB_PASSWORD: admin 
      DB_HOST: db
      DB_PORT: 5432
      BONITA_URL: http://192.168.100.7:8080
    volumes:
      - static-volume:/home/app/web/staticfiles
      - static-media:/home/app/web/mediafiles
    networks:
      mynetwork:
        ipv4_address: 172.25.0.3  # Assign the desired IP address
  
  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ljj_muebles
      POSTGRES_USER: ljj_muebles
      POSTGRES_PASSWORD: admin
    volumes:
      - db-volume:/var/lib/postgresql/data/
    networks:
      mynetwork:
        ipv4_address: 172.25.0.4  # Assign the desired IP address
  
  nginx:
    container_name: nginx 
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static-volume:/home/app/web/staticfiles
      - static-media:/home/app/web/mediafiles
    networks:
      mynetwork:
        ipv4_address: 172.25.0.5  # Assign the desired IP address

volumes:
  db-volume:
  static-volume:
  static-media:

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24 # Define your custom subnet and CIDR notation
