apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: registry.digitalocean.com/ljjmuebles/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: ljj_muebles
        - name: DB_USER
          value: ljj_muebles
        - name: DB_PASSWORD
          value: admin
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "5432"
        - name: BONITA_URL
          value: http://192.168.100.7:8080
        volumeMounts:
        - name: static-volume
          mountPath: /home/app/web/staticfiles
        - name: static-media
          mountPath: /home/app/web/mediafiles
      volumes:
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-volume
          readOnly: false  # Adjust if needed
      - name: static-media
        persistentVolumeClaim:
          claimName: static-media
          readOnly: false  # Adjust if needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi
