# nginx-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-2
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;

            location /api {
                proxy_pass http://api:8000;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_redirect off;
            }

            location / {
                proxy_pass http://api:8000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_redirect off;
            }

            location /api/static/ {
                alias /home/app/web/staticfiles/;
                types {
                    text/css css;
                    # Add other MIME types as needed
                }
            }

            location /api/media/ {
                alias /home/app/web/mediafiles/;
            }
        }
    }

---
# templates/nginx-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "nginx-proveedores"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proveedores
  template:
    metadata:
      labels:
        app: nginx-proveedores
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-2
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: static-volume-2
              mountPath: /home/app/web/staticfiles/  # Change this path according to your nginx setup
      volumes:
        - name: nginx-config-2
          configMap:
            name: nginx-config-2
        - name: static-volume-2
          persistentVolumeClaim:
            claimName: static-volume-2