apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db # Match the labels in your PostgreSQL stateful set
  ports:
    - protocol: TCP
      port: 5432 # Port used by PostgreSQL
  type: ClusterIP # Expose the service as ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: db2
spec:
  selector:
    app: db2 # Match the labels in your PostgreSQL stateful set
  ports:
    - protocol: TCP
      port: 5432 # Port used by PostgreSQL
  type: ClusterIP # Expose the service as ClusterIP